- bgp_address_family
- bgp_global
- interfaces
- l2_interfaces
- l3_interfaces
- ospfv2
- ospfv3
- build_info:
    internal_build_id: 2f026fab-f3ea-4171-9e76-42c5c3dedf3e
    internal_build_version: 4.24.6M-22486697.4246M
  device_name: eos-switch
  hardware:
    mac_address: 5254.00d9.190b
  memory:
    free_mb: 1270.4921875
    total_mb: 1967.21484375
  system:
    architecture: i686
    mac_address: 5254.00d9.190b
  uptime:
    days: 1
    hours: 7
    minutes: 9
    weeks: 0
  version: 4.24.6M
